spring:
  cloud:
    gateway:
      routes:
        - id: sharedCar
          uri: lb://sharedCar
        # uri: lb://sharedCar
          order: 40 #路由级别,优先匹配路由规则。数字越小优先匹配。
          predicates: 
            - Path=/sharedcar/**
            - Weight=service1, 100
          filters:
          - StripPrefix=1

          
        - id: sharedCar1
          uri: http://192.168.39.67:9008/shacar/,http://192.168.39.69:9008/shacar/
        # uri: lb://sharedCar
          order: 60 #路由级别
          predicates: 
            - Path=/sharedcar/**
            - Weight=service1, 0
          filters:
          - StripPrefix=1
          
       
        - id: authority
          uri: lb://authority
          order: 100 #路由级别
          predicates:
          #  - Method=*
            - Path=/**
          filters:
              # 熔断降级配置
            - name: Hystrix
              args:
               name : default
               fallbackUri: 'forward:/gateway/error'  
             
            - name: Retry
              args:
               retries: 3
               series:
                  - SERVER_ERROR

         
              
              
